{
  "VPN": {
    "AntiVPN": false,
    "WhiteListVPN": [
      "1.1.1.1",
      "0.0.0.0"
    ]
  },
  "Logs": {
    "HideIpInLogs": {
      "ConnectionLogs": false,
      "BanLogs": false,
      "AdminLogs": false,
      "OtherLogs": false,
      "ObjectsAiLogs": false
    },
    "ExplosionsLogs": true,
    "WebhookExplosionsLogs": "",
    "JoinLogs": true,
    "WebhookJoinLogs": "",
    "WebhookAdminFunctionsLogs": "",
    "WebhookLogs": "",
    "WebhookBanLogs": "",
    "WebhookScreenshotsStorage": "",
    "ObjectsAIDetectionLog": true,
    "WebhookObjectsAIDetectionLogs": "",
    "LogsConsole": true,
    "LogsConsoleList": {
      "PlayerBanned": true,
      "PlayerConnecting": false,
      "PlayerConnectionBlocked": true,
      "PlayerConnectionWithAdminMenuPerms": false
    }
  },
  "Peds": {
    "AntiPedWithBlacklistedWeapon": true,
    "BlacklistedWeaponsForPeds": [],
    "ExcludeEngineCreatedPeds": true,
    "BlockEngineCreatedPeds": false,
    "RemovePedsMarkedAsNoLongerNeeded": true
  },
  "EntityDetection": {
    "EntityDetection": true,
    "ObjectsAIDetection": true,
    "ObjectsAIResourceWhitelist": [
      "animals",
      "arena",
      "boosting",
      "cemitery",
      "creative",
      "inventory",
      "taxi",
      "lb-phone",
      "fivem",
      "garages",
      "pdm",
      "towed",
      "animacoes",
      "christmas",
      "farmer",
      "helicrash",
      "luckywheel",
      "marriage",
      "moneywash",
      "plants",
      "races",
      "radio",
      "skinweapon",
      "slotmachine",
      "vrp",
      "target",
      "dpemotes",
      "lafy"
    ],
    "ObjectsAIModelsWhitelist": [],
    "AntiWeirdObjectsSpawn": true,
    "AntiAggressivePeds": true,
    "AntiLaunchPlayer": true,
    "EntityDetectionBan": true,
    "EntityLockdownMode": "inactive",
    "AntiAttachEntityToPlayer": true,
    "AntiAttachEntityToPlayerModelsWhiteList": [],
    "MassPedsMaxValue": 100,
    "MassPedsResetCounterAfter": 1,
    "MassVehiclesMaxValue": 25,
    "MassVehiclesResetCounterAfter": 1,
    "MassEntitiesMaxValue": 100,
    "MassEntitiesResetCounterAfter": 1,
    "EntityDetectionMethod": "blacklist",
    "IgnoreVehiclesInWhiteListMode": false,
    "EntityDetectionList": [],
    "AntiMassSameEntitiesSpam": {
      "ban": true,
      "kick": true,
      "MaxValue": 25,
      "ResetCounterAfter": 4,
      "log": true,
      "enabled": true
    },
    "AntiMassSamePedsSpam": {
      "ban": true,
      "kick": true,
      "MaxValue": 25,
      "ResetCounterAfter": 4,
      "log": true,
      "enabled": true
    },
    "AntiMassSameVehiclesSpam": {
      "ban": true,
      "kick": true,
      "MaxValue": 3,
      "ResetCounterAfter": 12,
      "log": true,
      "enabled": true
    },
    "IgnoreEntitiesInAntiMassSpawn": []
  },
  "Explosions": {
    "ExplosionProtection": true,
    "AIExplosionDetection": false,
    "AIExplosionDetectionWhitelist": [
      "11",
      "67",
      "2",
      "27",
      "3",
      "12"
    ],
    "CancelAllExplosions": true,
    "CancelAllFires": false,
    "BlockInvisibleExplosions": true,
    "BlockSilentExplosions": true,
    "AntiMassExplosion": true,
    "MassExplosionValue": 20,
    "MassExplosionResetCounterAfter": 4,
    "ExplosionsList": {
      "0": {
        "name": "GRENADE",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": true,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "1": {
        "name": "GRENADELAUNCHER",
        "log": true,
        "ban": true,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "2": {
        "name": "STICKYBOMB",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "3": {
        "name": "MOLOTOV",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": true,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "4": {
        "name": "ROCKET",
        "log": true,
        "ban": true,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 5,
        "MassExplosionResetCounterAfter": 20
      },
      "5": {
        "name": "TANKSHELL",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "6": {
        "name": "HI_OCTANE",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "7": {
        "name": "CAR",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "8": {
        "name": "PLANE",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "9": {
        "name": "PETROL_PUMP",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": true,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "10": {
        "name": "BIKE",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "11": {
        "name": "DIR_STEAM",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "12": {
        "name": "DIR_FLAME",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": true,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "13": {
        "name": "DIR_WATER_HYDRANT",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": true,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "14": {
        "name": "DIR_GAS_CANISTER",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "15": {
        "name": "BOAT",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "16": {
        "name": "SHIP_DESTROY",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "17": {
        "name": "TRUCK",
        "log": true,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "18": {
        "name": "BULLET",
        "log": true,
        "ban": true,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "19": {
        "name": "SMOKEGRENADELAUNCHER",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "20": {
        "name": "SMOKEGRENADE",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "21": {
        "name": "BZGAS",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "22": {
        "name": "FLARE",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "23": {
        "name": "GAS_CANISTER",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "24": {
        "name": "EXTINGUISHER",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "25": {
        "name": "_0x988620B8",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "26": {
        "name": "EXP_TAG_TRAIN",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "27": {
        "name": "EXP_TAG_BARREL",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "28": {
        "name": "EXP_TAG_PROPANE",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": true,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "29": {
        "name": "EXP_TAG_BLIMP",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "30": {
        "name": "EXP_TAG_DIR_FLAME_EXPLODE",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "31": {
        "name": "EXP_TAG_TANKER",
        "log": true,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "32": {
        "name": "PLANE_ROCKET",
        "log": true,
        "ban": true,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "33": {
        "name": "EXP_TAG_VEHICLE_BULLET",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "34": {
        "name": "EXP_TAG_GAS_TANK",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "35": {
        "name": "EXP_TAG_BIRD_CRAP",
        "log": false,
        "ban": false,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "36": {
        "name": "EXP_TAG_RAILGUN",
        "log": true,
        "ban": true,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "37": {
        "name": "EXP_TAG_BLIMP2",
        "log": true,
        "ban": true,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "38": {
        "name": "EXP_TAG_FIREWORK",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "39": {
        "name": "EXP_TAG_SNOWBALL",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "40": {
        "name": "EXP_TAG_PROXMINE",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "41": {
        "name": "EXP_TAG_VALKYRIE_CANNON",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "42": {
        "name": "EXP_TAG_AIR_DEFENCE",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "43": {
        "name": "EXP_TAG_PIPEBOMB",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "44": {
        "name": "EXP_TAG_VEHICLEMINE",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "45": {
        "name": "EXP_TAG_EXPLOSIVEAMMO",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "46": {
        "name": "EXP_TAG_APCSHELL",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "47": {
        "name": "EXP_TAG_BOMB_CLUSTER",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "48": {
        "name": "EXP_TAG_BOMB_GAS",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "49": {
        "name": "EXP_TAG_BOMB_INCENDIARY",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "50": {
        "name": "EXP_TAG_BOMB_STANDARD",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "51": {
        "name": "EXP_TAG_TORPEDO",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "52": {
        "name": "EXP_TAG_TORPEDO_UNDERWATER",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "53": {
        "name": "EXP_TAG_BOMBUSHKA_CANNON",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "54": {
        "name": "EXP_TAG_BOMB_CLUSTER_SECONDARY",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "55": {
        "name": "EXP_TAG_HUNTER_BARRAGE",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "56": {
        "name": "EXP_TAG_HUNTER_CANNON",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "57": {
        "name": "EXP_TAG_ROGUE_CANNON",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "58": {
        "name": "EXP_TAG_MINE_UNDERWATER",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "59": {
        "name": "EXP_TAG_ORBITAL_CANNON",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "60": {
        "name": "EXP_TAG_BOMB_STANDARD_WIDE",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "61": {
        "name": "EXP_TAG_EXPLOSIVEAMMO_SHOTGUN",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "62": {
        "name": "EXP_TAG_OPPRESSOR2_CANNON",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "63": {
        "name": "EXP_TAG_MORTAR_KINETIC",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "64": {
        "name": "EXP_TAG_VEHICLEMINE_KINETIC",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "65": {
        "name": "EXP_TAG_VEHICLEMINE_EMP",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "66": {
        "name": "EXP_TAG_VEHICLEMINE_SPIKE",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "67": {
        "name": "EXP_TAG_VEHICLEMINE_SLICK",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "68": {
        "name": "EXP_TAG_VEHICLEMINE_TAR",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "69": {
        "name": "EXP_TAG_SCRIPT_DRONE",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "70": {
        "name": "EXP_TAG_RAYGUN",
        "log": true,
        "ban": true,
        "block": true,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "71": {
        "name": "EXP_TAG_BURIEDMINE",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "72": {
        "name": "EXP_TAG_SCRIPT_MISSILE",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "73": {
        "name": "EXP_TAG_RCTANK_ROCKET",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "74": {
        "name": "EXP_TAG_BOMB_WATER",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "75": {
        "name": "EXP_TAG_BOMB_WATER_SECONDARY",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "76": {
        "name": "_0xF728C4A9",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "77": {
        "name": "_0xBAEC056F",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "78": {
        "name": "EXP_TAG_FLASHGRENADE",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "79": {
        "name": "EXP_TAG_STUNGRENADE",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "80": {
        "name": "_0x763D3B3B",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "81": {
        "name": "EXP_TAG_SCRIPT_MISSILE_LARGE",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      },
      "82": {
        "name": "EXP_TAG_SUBMARINE_BIG",
        "log": false,
        "ban": false,
        "block": false,
        "ExcludeFromGlobalMassExplosion": false,
        "MassExplosionValue": 20,
        "MassExplosionResetCounterAfter": 20
      }
    }
  },
  "Particles": {
    "ParticlesDetection": true,
    "AntiSpawnParticleOnNonOwnedEntity": false,
    "AntiMassParticles": true,
    "ParticlesMaxScale": 4,
    "MassParticlesValue": 50,
    "MassParticlesResetCounterAfter": 2,
    "ParticlesIgnoreList": []
  },
  "Permissions": {
    "AlternativePermissionsCheck": false,
    "AlternativePermissions": {}
  },
  "SafeEvents": {
    "SafeEvents": true,
    "ExtendedSecurity": false,
    "ExtendedSecurityMode": "relaxed",
    "IgnoreSecurityEventsList": [],
    "IgnoreEventsList": []
  },
  "Events": {
    "BlacklistedStringEvent": true,
    "BlacklistedTriggersTable": [
      "yourweapons",
      "rpv_uber:success",
      "xex_streetfight:pay",
      "lester:vendita",
      "esx:jackingcar",
      "esx_vehicletrunk:giveDirty",
      "esx_moneywash:deposit",
      "Esx-MenuPessoal:Boss_recruterplayer",
      "esx_blackmoney:washMoney",
      "esx_ambulancejob:setDeathStatus",
      "esx_carthief:alertcops",
      "esx_dmvschool:addLicense",
      "esx_skin:setPlayerInvisible",
      "esx_bank:withdraw",
      "esx:enterpolicecar",
      "esx_handcuffs:cuffing",
      "esx_jail:sendToJail",
      "esx_jail:unjailQuest",
      "esx_jailer:unjailTime",
      "esx_mecanojob:onNPCJobCompleted",
      "esx_mechanicjob:startHarvest",
      "esx_mechanicjob:startCraft",
      "esx-qalle-hunting:reward",
      "esx-qalle-hunting:sell",
      "esx_skin:responseSaveSkin",
      "esx_society:setJob",
      "esx_skin:responseSaDFWMveSkin",
      "esx_dmvschool:addLiceDFWMnse",
      "esx_mechanicjob:starDFWMtCraft",
      "esx_drugs:startHarvestWDFWMeed",
      "esx_drugs:startTransfoDFWMrmWeed",
      "esx_drugs:startSellWeDFWMed",
      "esx_drugs:startHarvestDFWMCoke",
      "esx_drugs:startTransDFWMformCoke",
      "esx_drugs:startSellCDFWMoke",
      "esx_drugs:startHarDFWMvestMeth",
      "esx_drugs:startTDFWMransformMeth",
      "esx_drugs:startSellMDFWMeth",
      "esx_drugs:startHDFWMarvestOpium",
      "esx_drugs:startSellDFWMOpium",
      "esx_drugs:starDFWMtTransformOpium",
      "esx_blanchisDFWMseur:startWhitening",
      "esx_drugs:stopHarvDFWMestCoke",
      "esx_drugs:stopTranDFWMsformCoke",
      "esx_drugs:stopSellDFWMCoke",
      "esx_drugs:stopHarvesDFWMtMeth",
      "esx_drugs:stopTranDFWMsformMeth",
      "esx_drugs:stopSellMDFWMeth",
      "esx_drugs:stopHarDFWMvestWeed",
      "esx_drugs:stopTDFWMransformWeed",
      "esx_drugs:stopSellWDFWMeed",
      "esx_drugs:stopHarvestDFWMOpium",
      "esx_drugs:stopTransDFWMformOpium",
      "esx_drugs:stopSellOpiuDFWMm",
      "esx_society:openBosDFWMsMenu",
      "esx_tankerjob:DFWMpay",
      "esx_vehicletrunk:givDFWMeDirty",
      "esx_vehicleshop:setVehicleOwnedPlayerId",
      "esx_drugs:pickedUpCDFWMannabis",
      "esx_drugs:processCDFWMannabis",
      "esx-qalle-hunting:DFWMreward",
      "esx-qalle-hunting:seDFWMll",
      "esx_mecanojob:onNPCJobCDFWMompleted",
      "esx_society:putVehicleDFWMInGarage",
      "esx:clientLog",
      "esx:triggerServerCallback",
      "esx:setJob",
      "checkpolice:antiplayerLoaded",
      "esx:playerLoaded",
      "esx:createMissingPickups",
      "esx:updateLoadout",
      "esx:updateLastPosition",
      "esx:removeInventoryItem",
      "esx:useItem",
      "esx:onPickup",
      "esx_jobs:startWork",
      "esx_jobs:stopWork",
      "esx_fueldDFWMelivery:pay",
      "esx_carthDFWMief:pay",
      "esx_godiDFWMrtyjob:pay",
      "esx_pizza:pDFWMay",
      "esx_ranger:pDFWMay",
      "esx_garbageDFWMjob:pay",
      "esx_truckDFWMerjob:pay",
      "esx_jobs:caDFWMution",
      "esx_carthief:alertcoDFWMps",
      "esx:getShDFWMaredObjDFWMect",
      "esx_society:getOnlDFWMinePlayers",
      "esx_jailer:unjailTiDFWMme",
      "esx_ambulancejob:reDFWMvive",
      "esx_moneywash:depoDFWMsit",
      "esx_moneywash:witDFWMhdraw",
      "esx_handcuffs:cufDFWMfing",
      "esx_policejob:haDFWMndcuff",
      "esx-qalle-jail:jailPDFWMlayer",
      "esx_dmvschool:pDFWMay",
      "esx_biDFWMlling:sendBill",
      "esx_jDFWMailer:sendToJail",
      "esx_jaDFWMil:sendToJail",
      "esx_goDFWMpostaljob:pay",
      "esx_baDFWMnksecurity:pay",
      "esx_sloDFWMtmachine:sv:2",
      "esx:giDFWMveInventoryItem",
      "esx_vehicleshop:setVehicleOwnedDFWM",
      "esx_mafiajob:confiscateDFWMPlayerItem",
      "OG_cuffs:cuffCheckNearest",
      "CheckHandcuff",
      "arisonarp:wiezienie",
      "gambling:spend",
      "265df2d8-421b-4727-b01d-b92fd6503f5e",
      "mission:completed",
      "truckerJob:success",
      "c65a46c5-5485-4404-bacf-06a106900258",
      "paycheck:salary",
      "MF_MobileMeth:RewardPlayers",
      "lscustoms:UpdateVeh",
      "xk3ly-farmer:paycheck",
      "AdminMenu:giveDirtyMoney",
      "Tem2LPs5Para5dCyjuHm87y2catFkMpV",
      "dqd36JWLRC72k8FDttZ5adUKwvwq9n9m",
      "antilynxr4:detect",
      "antilynxr6:detection",
      "ynx8:anticheat",
      "antilynx8r4a:anticheat",
      "lynx8:anticheat",
      "AntiLynxR4:kick",
      "AntiLynxR4:log",
      "esx_spectate:kick",
      "Banca:withdraw",
      "BsCuff:Cuff696999",
      "cuffServer",
      "cuffGranted",
      "DFWM:adminmenuenable",
      "DFWM:askAwake",
      "DFWM:checkup",
      "DFWM:cleanareaentity",
      "DFWM:cleanareapeds",
      "DFWM:cleanareaveh",
      "DFWM:enable",
      "DFWM:invalid",
      "DFWM:log",
      "DFWM:openmenu",
      "DFWM:spectate",
      "DFWM:ViolationDetected",
      "eden_garage:payhealth",
      "ems:revive",
      "hentailover:xdlol",
      "JailUpdate",
      "js:removejailtime",
      "LegacyFuel:PayFuel",
      "ljail:jailplayer",
      "mellotrainer:adminTempBan",
      "mellotrainer:adminKick",
      "mellotrainer:s_adminKill",
      "NB:destituerplayer",
      "NB:recruterplayer",
      "paramedic:revive",
      "police:cuffGranted",
      "unCuffServer",
      "uncuffGranted",
      "whoapd:revive",
      "lscustoms:pDFWMayGarage",
      "vrp_slotmachDFWMine:server:2",
      "Banca:dDFWMeposit",
      "bank:depDFWMosit",
      "give_back",
      "AdminMeDFWMnu:giveBank",
      "AdminMDFWMenu:giveCash",
      "NB:recDFWMruterplayer",
      "LegacyFuel:PayFuDFWMel",
      "OG_cuffs:cuffCheckNeDFWMarest",
      "CheckHandcDFWMuff",
      "cuffSeDFWMrver",
      "cuffGDFWMranted",
      "police:cuffGDFWMranted",
      "bank:withdDFWMraw",
      "dmv:succeDFWMss",
      "gambling:speDFWMnd",
      "AdminMenu:giveDirtyMDFWMoney",
      "mission:completDFWMed",
      "truckerJob:succeDFWMss",
      "99kr-burglary:addMDFWMoney",
      "DiscordBot:plaDFWMyerDied",
      "js:jaDFWMiluser",
      "h:xd",
      "adminmenu:setsalary",
      "adminmenu:cashoutall",
      "bank:tranDFWMsfer",
      "paycheck:bonDFWMus",
      "paycheck:salDFWMary",
      "HCheat:TempDisableDetDFWMection",
      "BsCuff:Cuff696DFWM999",
      "veh_SR:CheckMonDFWMeyForVeh",
      "mellotrainer:adminTeDFWMmpBan",
      "mellotrainer:adminKickDFWM",
      "tigoanticheat:getSharedObject",
      "tigoanticheat:triggerServerCallback",
      "tigoanticheat:triggerServerEvent",
      "tigoanticheat:serverCallback",
      "tigoanticheat:triggerClientCallback",
      "tigoanticheat:clientCallback",
      "tigoanticheat:getServerConfig",
      "tigoanticheat:banPlayer",
      "tigoanticheat:playerResourceStarted",
      "tigoanticheat:logToConsole",
      "tigoanticheat:stillAlive",
      "tigoanticheat:storeSecurityToken",
      "modmenu",
      "esx:getSharedObject",
      "esx_ambulancejob:revive",
      "esx_society:openBossMenu",
      "esx_status:set",
      "esx_policejob:handcuff",
      "esx_handcuffs:cuffClosestPlayer",
      "LegacyFuel:RefundFuel",
      "esx_jailer:wysylandoo",
      "esx_godirtyjob:pay",
      "esx_pizza:pay",
      "esx_slotmachine:sv:2",
      "esx_banksecurity:pay",
      "esx_truckerjob:pay",
      "esx_carthief:pay",
      "esx_garbagejob:pay",
      "esx_ranger:pay",
      "esx_truckersjob:payy",
      "esx_blanchisseur:washMoney",
      "esx_moneywash:withdraw",
      "esx_blanchisseur:startWhitening",
      "esx_billing:sendBill",
      "esx_dmvschool:pay",
      "esx_jailer:sendToJail",
      "esx_jailler:sendToJail",
      "esx-qalle-jail:jailPlayer",
      "esx-qalle-jail:jailPlayerNew",
      "esx_jailer:sendToJailCatfrajerze",
      "esx_policejob:billPlayer",
      "esx_skin:openRestrictedMenu",
      "esx_inventoryhud:openPlayerInventory",
      "bank:transfer",
      "advancedFuel:setEssence",
      "display",
      "tost:zgarnijsiano",
      "Sasaki_kurier:pay",
      "wojtek_ubereats:napiwek",
      "wojtek_ubereats:hajs",
      "xk3ly-barbasz:getfukingmony",
      "xk3ly-farmer:paycheck",
      "tostzdrapka:wygranko",
      "laundry:washcash",
      "projektsantos:mandathajs",
      "program-keycard:hacking",
      "6a7af019-2b92-4ec2-9435-8fb9bd031c26",
      "211ef2f8-f09c-4582-91d8-087ca2130157",
      "neweden_garage:pay",
      "8321hiue89js",
      "js:jailuser",
      "wyspa_jail:jailPlayer",
      "wyspa_jail:jail",
      "ambulancier:selfRespawn",
      "UnJP",
      "esx-qalle-jail:openJailMenu",
      "esx:spawnVehicle",
      "HCheat:TempDisableDetection",
      "bank:deposit",
      "bank:withdraw",
      "cacador-vender",
      "esx:giveInventoryItem",
      "esx_jobs:caution",
      "esx_fueldelivery:pay",
      "esx_society:getOnlinePlayers",
      "esx_vehicleshop:setVehicleOwned",
      "gcPhone:tchatchannel",
      "gcPhone:internalAddMessage",
      "AdminMenu:giveBank",
      "AdminMenu:giveCash",
      "vrp_slotmachine:server:2",
      "Banca:deposit",
      "lscustoms:payGarage",
      "LegacyFuel:PayFuel",
      "blarglebus:finishRoute",
      "dmv:success",
      "departamento-vender",
      "reanimar:pagamento",
      "adminmenu:allowall",
      "d0pamine_xyz:getFuckedNigger",
      "chat:server:ServerPSA",
      "antilynx8:anticheat",
      "DiscordBot:playerDie",
      "esx_fueldeliver",
      "PayForRepairNow",
      "esx_jobs:caution",
      "bank:transfer",
      "lscustoms:payGarag",
      "esx_vangelico_robbery:gioielli1",
      "99kr-burglary:addMoney",
      "esx_truckerJob2:payout",
      "es_truckerJob:pay",
      "burglary:money",
      "lenzh_chopshop:sell",
      "esx_deliveries:AddCashMoney",
      "loffe_prisonwork",
      "esx_tankerjob:pay",
      "esx_society:sendMoney",
      "esx_drugs:sellAll",
      "esx_drugs:sellCocaine",
      "esx_drugs:sellCoke",
      "esx_drugs:sellWeed",
      "esx_drugs:sellMeth",
      "esx_drugs:sellOpium",
      "esx_mechanicjob:repairCurrentVehicle",
      "napadtransport:graczZrobilnapad",
      "tost:zgarnijsiano",
      "esx_loffe_fangelse:Pay",
      "esx_mugging:giveMoney",
      "esx_robnpc:giveMoney",
      "esx_vehicletrunk:giveDirty",
      "esx_gopostaljob:pay",
      "f0ba1292-b68d-4d95-8823-6230cdf282b6",
      ":tunnel_req",
      "gambling:spend",
      "265df2d8-421b-4727-b01d-b92fd6503f5e",
      "AdminMenu:giveDirtyMoney",
      "esx_moneywash:deposit",
      "esx_moneywash:withdraw",
      "esx_moneywash:deposit",
      "mission:completed",
      "truckerJob:success",
      "esx_moneywash:getMoney",
      "AdminMenu:addMoney",
      "esx_fishing:receiveFish",
      "c65a46c5-5485-4404-bacf-06a106900258",
      "dropOff",
      "truckerfuel:success",
      "delivery:success",
      "esx_brinksjob:pay",
      "esx_postejob:pay",
      "esx_garbage:pay",
      "esx_carteirojob:pay",
      "esx_pilot:success",
      "esx_taxijob:success",
      "adminmenu:setsalary",
      "esx_mugging:giveMoney",
      "paycheck:salary",
      "vrp_slotmachine:server:2",
      "DiscordBot:playerDied",
      "esx_drugs:startHarvestWeed",
      "esx_drugs:startTransformWeed",
      "esx_drugs:startSellWeed",
      "esx_drugs:startHarvestCoke",
      "esx_drugs:startTransformCoke",
      "esx_drugs:startSellCoke",
      "esx_drugs:startHarvestMeth",
      "esx_drugs:startTransformMeth",
      "esx_drugs:startSellMeth",
      "esx_drugs:startHarvestOpium",
      "esx_drugs:startTransformOpium",
      "esx_drugs:startSellOpium",
      "esx_drugs:stopTransformCoke",
      "esx_handcuffs:unlocking",
      "esx_policejob:requestarrest",
      "esx_policejob:handcuffPasta",
      "17A34C820A685513C5B4ADDD85968B9E905CC300A261EB55D299ABCB6C90AAA872712B3B6C13DC41913FCC2BE84A07EF9300DC4E89669A4B0E6FBB344A69D239",
      "llotrainer:adminKick",
      "esx_mafiajob:confiscatePlayerItem",
      "InteractSound_SV:PlayOnAll",
      "SEM_InteractionMenu:Jail",
      "SEM_InteractionMenu:DragNear",
      "KorioZ-PersonalMenu:Weapon_addAmmoToPedS",
      "KorioZ-PersonalMenu:Admin_BringS",
      "KorioZ-PersonalMenu:Admin_giveCash",
      "KorioZ-PersonalMenu:Admin_giveBank",
      "KorioZ-PersonalMenu:Admin_giveDirtyMoney",
      "KorioZ-PersonalMenu:Boss_promouvoirplayer",
      "KorioZ-PersonalMenu:Boss_destituerplayer",
      "KorioZ-PersonalMenu:Boss_recruterplayer",
      "KorioZ-PersonalMenu:Boss_virerplayer",
      "Admin2Menu:giveCash",
      "Admin2Menu:giveBank",
      "Admin2Menu:giveDirtyMoney",
      "SEM_InteractionMenu:CuffNear",
      "SEM_InteractionMenu:SeatNear",
      "SEM_InteractionMenu:UnseatNear",
      "SEM_InteractionMenu:Unjail",
      "SEM_InteractionMenu:Hospitalize",
      "SEM_InteractionMenu:Unhospitalize",
      "FAC:EzExec",
      "redst0nia:checking"
    ],
    "BlacklistedTriggers": true,
    "BlacklistedStringEventList": [
      "Mod Menu",
      "You got fucked",
      "ATG",
      "anticheat",
      "FIVEGUARD",
      "fiveguard",
      "fiveguard.net",
      "cheat",
      "Fuck This",
      "discord.gg",
      "Lynx",
      "Huge",
      "Brutan",
      "lynxmenu",
      "API-AC",
      "https://",
      "http://",
      "EULEN",
      "hammafia",
      "onion",
      "executor",
      "desudo",
      "unex"
    ],
    "EventsRateLimiter": true,
    "RateLimiterEventsList": {
      "esx_illegal_drugs:startHarvestWeed": {
        "limit": 3,
        "ResetDelay": 3
      },
      "esx_drugs:pickedUpCannabis": {
        "limit": 3,
        "ResetDelay": 3
      },
      "esx_drugs:startHarvestWeed": {
        "limit": 3,
        "ResetDelay": 3
      },
      "esx_drugs:startHarvestCoke": {
        "limit": 3,
        "ResetDelay": 3
      },
      "esx_blanchisseur:startWhitening": {
        "limit": 3,
        "ResetDelay": 3
      },
      "esx_fueldelivery:pay": {
        "limit": 2,
        "ResetDelay": 3
      },
      "esx_carthief:pay": {
        "limit": 2,
        "ResetDelay": 3
      },
      "esx_godirtyjob:pay": {
        "limit": 2,
        "ResetDelay": 3
      },
      "esx_pizza:pay": {
        "limit": 2,
        "ResetDelay": 3
      },
      "esx_ranger:pay": {
        "limit": 2,
        "ResetDelay": 3
      },
      "esx_garbagejob:pay": {
        "limit": 2,
        "ResetDelay": 3
      },
      "esx_slotmachine:sv:2": {
        "limit": 2,
        "ResetDelay": 3
      },
      "esx_dmvschool:pay": {
        "limit": 2,
        "ResetDelay": 3
      },
      "esx_truckerjob:pay": {
        "limit": 2,
        "ResetDelay": 3
      },
      "esx_gopostaljob:pay": {
        "limit": 2,
        "ResetDelay": 3
      },
      "esx_tankerjob:pay": {
        "limit": 2,
        "ResetDelay": 3
      },
      "esx_society:billing": {
        "limit": 2,
        "ResetDelay": 3
      },
      "esx_policejob:message": {
        "limit": 4,
        "ResetDelay": 3
      },
      "esx_blanchisseur:washMoney": {
        "limit": 3,
        "ResetDelay": 3
      },
      "esx_blackmoney:washMoney": {
        "limit": 3,
        "ResetDelay": 3
      },
      "esx_moneywash:withdraw": {
        "limit": 3,
        "ResetDelay": 3
      },
      "laundry:washcash": {
        "limit": 3,
        "ResetDelay": 3
      },
      "esx_policejob:handcuff": {
        "limit": 5,
        "ResetDelay": 3
      },
      "esx_handcuffs:cuffing": {
        "limit": 5,
        "ResetDelay": 3
      },
      "gcPhone:_internalAddMessage": {
        "limit": 3,
        "ResetDelay": 3
      },
      "gcPhone:tchat_channel": {
        "limit": 3,
        "ResetDelay": 3
      },
      "js:jailuser": {
        "limit": 2,
        "ResetDelay": 3
      },
      "ljail:jailplayer": {
        "limit": 2,
        "ResetDelay": 3
      },
      "esx_jail:sendToJail": {
        "limit": 2,
        "ResetDelay": 3
      },
      "esx_illegal_drugs:startHarvestCoke": {
        "limit": 3,
        "ResetDelay": 3
      },
      "esx_drugs:startHarvestMeth": {
        "limit": 3,
        "ResetDelay": 3
      },
      "esx_illegal_drugs:startHarvestMeth": {
        "limit": 3,
        "ResetDelay": 3
      },
      "esx_drugs:startHarvestOpium": {
        "limit": 3,
        "ResetDelay": 3
      },
      "esx_illegal_drugs:startHarvestOpium": {
        "limit": 3,
        "ResetDelay": 3
      },
      "esx_jailer:sendToJail": {
        "limit": 2,
        "ResetDelay": 3
      },
      "esx-qalle-jail:jailPlayer": {
        "limit": 2,
        "ResetDelay": 3
      },
      "esx:setjob": {
        "limit": 3,
        "ResetDelay": 3
      },
      "qb-smallresources:server:additem": {
        "limit": 3,
        "ResetDelay": 3
      },
      "player:receiveitem": {
        "limit": 3,
        "ResetDelay": 3
      },
      "esx_ambulancejob:setdeathstatus": {
        "limit": 3,
        "ResetDelay": 3
      },
      "zv_elektromonteur:paymoney": {
        "limit": 3,
        "ResetDelay": 3
      },
      "inside-gardener:payoutnow": {
        "limit": 3,
        "ResetDelay": 3
      },
      "cfx-hu-ems:heal": {
        "limit": 3,
        "ResetDelay": 3
      },
      "fuel:pay": {
        "limit": 3,
        "ResetDelay": 3
      },
      "bounty:giveitem": {
        "limit": 3,
        "ResetDelay": 3
      },
      "utk_oh:rewardcash": {
        "limit": 3,
        "ResetDelay": 3
      },
      "casino:tradeinchips": {
        "limit": 3,
        "ResetDelay": 3
      },
      "esx_ambulancejob:revive": {
        "limit": 3,
        "ResetDelay": 3
      },
      "esx-qalle-jail:prisonworkreward": {
        "limit": 3,
        "ResetDelay": 3
      },
      "ox_inventory:giveitem": {
        "limit": 3,
        "ResetDelay": 3
      },
      "d-phone:client:message:senddispatch": {
        "limit": 3,
        "ResetDelay": 3
      },
      "esx_billing:sendbill": {
        "limit": 3,
        "ResetDelay": 3
      },
      "xfsd-listing:getnewjob": {
        "limit": 3,
        "ResetDelay": 3
      },
      "esx_yacht:reward": {
        "limit": 3,
        "ResetDelay": 3
      },
      "esx_marvin_stable_lateral_position:medic": {
        "limit": 3,
        "ResetDelay": 3
      },
      "okokbanking:depositmoney": {
        "limit": 3,
        "ResetDelay": 3
      },
      "tfoadakgt9vdu": {
        "limit": 3,
        "ResetDelay": 3
      },
      "esx_vangelico_robbery:gioielli": {
        "limit": 3,
        "ResetDelay": 3
      },
      "postal_job:end": {
        "limit": 3,
        "ResetDelay": 3
      },
      "mkbuss:givereward": {
        "limit": 3,
        "ResetDelay": 3
      },
      "fp-jobs:rewardfisher": {
        "limit": 3,
        "ResetDelay": 3
      },
      "esx_advancedgarage:payhealth": {
        "limit": 3,
        "ResetDelay": 3
      },
      "esx:spawnvehicle": {
        "limit": 3,
        "ResetDelay": 3
      }
    }
  },
  "Basic": {
    "KeepAliveSystem": true,
    "KeepAliveSystemMode": 1,
    "KeepAliveTimeout": 60000,
    "KeepAliveSystemBan": false,
    "DiscordInviteCode": "eldoradorp",
    "AdvancedBanLogic": true,
    "Language": "br (Brazilian Portuguese)",
    "AntiPlayerKill": true,
    "RequiredIdentifiers": true,
    "RequiredIdentifiersTypes": {
      "steam": true,
      "license": false,
      "discord": false,
      "xbl": false,
      "liveid": false,
      "ip": false,
      "fivem": false
    },
    "AntiCipherOnResourceStart": false,
    "DisableSoundEventRouting": true,
    "DisablePhoneExplosionRouting": false,
    "DisableScriptEntityStateRouting": true,
    "SanitizeRagdollEvents": true,
    "AntiRemoveWeaponFromPed": true,
    "AdvancedAntiGiveWeapon": true,
    "AntiFakeChat": true,
    "BlacklistedStringsInNames": false,
    "BlacklistedStringsInNamesList": [],
    "AntiStopStartResources": false,
    "ClearPedTasksImmediatelyLog": true,
    "ClearPedTasksImmediatelyBan": true,
    "ClearPedTasksImmediatelyDistance": 8,
    "BanOnIPAddress": true,
    "AntiSpawnPropsByUnauthorizedResources": true,
    "AntiSpawnPropsByUnauthorizedResourcesMode": 1,
    "AntiSpawnPropsByUnauthorizedResourcesMode2Table": [
      "animals",
      "arena",
      "boosting",
      "cemitery",
      "creative",
      "inventory",
      "taxi",
      "lb-phone",
      "fivem",
      "garages",
      "pdm",
      "towed",
      "animacoes",
      "christmas",
      "farmer",
      "helicrash",
      "luckywheel",
      "marriage",
      "moneywash",
      "plants",
      "races",
      "radio",
      "skinweapon",
      "slotmachine",
      "vrp",
      "target",
      "dpemotes",
      "lafy"
    ],
    "DestroyedVehicleDelete": false
  },
  "ESX": {
    "ESX": false,
    "ESXScriptName": "es_extended",
    "SharedObjectEvent": "esx:getSharedObject",
    "AutoPermissionGroupSetter": false,
    "WhiteListEventsOnJob": false,
    "WhiteListEventsOnJobList": {
      "test": {
        "JobName": [
          "police"
        ]
      }
    },
    "AntiSpoofedWeapons": false,
    "AntiGiveWeaponESX": false,
    "IgnoreWeaponsListFromAntiGiveWeapon": [
      "WEAPON_PETROLCAN"
    ]
  },
  "QBCore": {
    "QBCore": false,
    "QBCoreScriptName": "qb-core",
    "SharedObjectEvent": "QBCore:GetObject",
    "WhiteListEventsOnJobList": {
      "test": {
        "JobName": [
          "police"
        ]
      }
    },
    "AntiGiveWeaponQBCore": false,
    "IgnoreWeaponsListFromAntiGiveWeapon": [
      "WEAPON_PETROLCAN"
    ]
  },
  "QBox": {
    "QBox": false,
    "QBoxScriptName": "qb-core",
    "WhiteListEventsOnJobList": {
      "test": {
        "JobName": [
          "police"
        ]
      }
    },
    "AntiGiveWeaponQBox": false,
    "IgnoreWeaponsListFromAntiGiveWeapon": [
      "WEAPON_PETROLCAN"
    ]
  },
  "Pickups": {
    "DisablePickupCollecting": true,
    "DeleteWeaponPickupCollect": true
  },
  "Client": {
    "AntiInternal": true,
    "CheatsDetection": true,
    "CheatsAiDetection": false,
    "AntiEulen": true,
    "ExtendedAntiLuaMenus": false,
    "AntiCrashPlayer": true,
    "AntiHXSpawn": true,
    "AntiTapiatoMenu": false,
    "CbScanner": true,
    "AntiMagneto": true,
    "AntiStealOutfit": false,
    "AntiHealthHack": true,
    "AntiHealthFullRecharge": true,
    "AntiArmourHack": true,
    "AntiGodmode": false,
    "AntiGodmodeTypes": {
      "1": true,
      "2": true,
      "3": true,
      "4": true
    },
    "AntiEulenGodmode": true,
    "AntiSemiGodMode": false,
    "AntiNoHeadshot": true,
    "AntiModifiedMeleeDamage": true,
    "AntiEditedHeadHitbox": true,
    "CitizenAntiDamageModifier": true,
    "CitizenAntiGiveWeapon": true,
    "AntiInfiniteStamina": false,
    "AntiAimbot": true,
    "AntiCitizenAimbot": true,
    "AntiCitizenMagicBullet": false,
    "AntiSilentAim": true,
    "AntiTaze": true,
    "AntiSpectate": true,
    "AntiTeleport": false,
    "AntiTeleportToVehicle": false,
    "AntiTeleportToWayPoint": true,
    "AntiAutoDrive": true,
    "AntiInvisible": false,
    "AntiSpeedhack": true,
    "AntiSuperJump": true,
    "AntiFreecam": false,
    "AntiFreecamAllowCoords": {},
    "AntiNightVision": true,
    "AntiThermalVision": true,
    "AntiNoclip": true,
    "AntiEulenNoclip": true,
    "AntiPlayerExplosion": true,
    "AntiNuiDevtools": true,
    "AntiNuiOfflineThrottling": false,
    "AntiCombatRoll": true,
    "AntiAttachPedToPlayer": true,
    "BlipsDetection": false,
    "BlipsValue": 10,
    "AntiEnterSoloSession": true,
    "BlacklistedTexturesList": [
      "HydroMenuHeader",
      "John2",
      "fs12",
      "fam_DUHSGOSDIUGIHOSDG",
      "logo",
      "ISMMENUHeader",
      "duiTex",
      "menu_bg",
      "logo",
      "logo1",
      "woof2",
      "adb831a7fdd83d_Guest_d1e2a309ce7591dff8Header6",
      "duiTex_DSIOGJSDG",
      "wm2",
      "NeekerMan1",
      "Blood-X ",
      "Dopameme ",
      "FalloutMenu ",
      "Lux meme",
      "Absolut ",
      "kekhack ",
      "maestro ",
      "skidmenu",
      "brutan ",
      "fivesense ",
      "NeekerMan1 ",
      "auttaja ",
      "bartowmenu ",
      "hoaxmenu",
      "fendin ",
      "Ham",
      "oblivious ",
      "malossimenu ",
      "Memeeee ",
      "Tiago ",
      "hydramenu ",
      "Swagamine",
      "HydroMenuHeader",
      "HydroMenuLogo ",
      "Terror Menu ",
      "lynxmenu",
      "Maestro 2.3 ",
      "ALIEN MENU",
      "HydroMenu",
      "~u~⚡️ALIEN MENU⚡️ ",
      "CopyCat",
      "dickmenu",
      "zykemboss",
      "wudywchuj",
      "x32tqaw",
      "negus",
      "KentasMenu",
      "thefov",
      "__REAPER5__",
      "__REAPER6__",
      "FixedLumia",
      "FixedLumia1",
      "FixedLumia2",
      "FixedLumia3",
      "FixedLumia4",
      "VertissoTrapersksk",
      "Vertissodafuq",
      "Kysnnmen",
      "negus",
      "ligma",
      "candice",
      "idkfuckthismenutbh",
      "wtfamidoinghere",
      "nigerus",
      "blacklisted",
      "watermark",
      "darkside",
      "dopatest",
      "vertissotraperdamnshit",
      "CopyCatHeader",
      "weapon_icons",
      "watermalone",
      "watermalone1",
      "deadline",
      "skript",
      "skirpt.gg",
      "Loader",
      "LoaderEnebled",
      "function asddadasdadButton",
      "ggZera.menu.groupbox",
      "GGzera | Premium Menu",
      "imagemBotaoOpc",
      "imagemMenuBackground",
      "imagemBotaoSlider",
      "leaderboard_kills_icon",
      "imagemCheckBoxOn",
      "imagemCheckBoxOff",
      "YOLO",
      "shop_new_star",
      "checkboxligada",
      "checkboxdesligada",
      "transport_car_icon",
      "leaderboard_friends_icon",
      "leaderboard_globe_icon",
      "leaderboard_position_icon",
      "mpcarhud",
      "nilsun",
      "meows",
      "TWOSTRINGS",
      "self12",
      "veiculos12",
      "arma1",
      "online122",
      "visual12",
      "misc122",
      "jwjwfjwfwhfhw",
      "imagemabasdois",
      "meow",
      "imagemabas",
      "mpleaderboard",
      "leaderboard_bikers_icon",
      "TigerInterface",
      "TigerInterfaceList",
      "TigerButton",
      "TigerToogle",
      "TigerFy",
      "pozegostosohmm",
      "pozedeliciahmm",
      "oihdsaoidhasodahdaodho",
      "sadoiadhaosidahgdidhahdoh",
      "butaozinho",
      "fm",
      "John",
      "Urubu",
      "Urubu3",
      "wave",
      "weaponicons",
      "hugeware3",
      "hugeware1",
      "hugeware",
      "ggZera.menu.groupbox",
      "function asddadasdad_Button",
      "iusadbaiusdbasidb_Velocidade",
      "Super_Velocidade",
      "player-sdfijsdfjidfsjin-fov",
      "player-sdfijsdfjidfsjin-speed",
      "nazwa",
      "adsadkapodkapsd",
      "WATAFAKMEN",
      "menuFocusBackgroundColor",
      "maxOptionCount",
      "menuFocusColor",
      "menuSubTextColor",
      "menuTextColor",
      "menuBackgroundColor",
      "titleBackgroundSprite",
      "titleBackgroundColor",
      "RadioDUI",
      "wofDUI",
      "WarMenu",
      "lysy3",
      "lysy2",
      "lysy",
      "lysy1",
      "mpweaponscommon",
      "visualflow",
      "mptattoos",
      "mpweaponsgang1",
      "mphud",
      "mpweaponsunusedfornow",
      "mpmissmarkers256",
      "corona_shade",
      "imagemMenu2",
      "Checkboxoff2",
      "CheckboxOn2",
      "RY4NMENUPNG",
      "BONEQUINHO",
      "BONEQUINHOVERMELHO",
      "ARMAFDS",
      "ARMAVERMELHA",
      "CARRO",
      "CARROVERM",
      "JOGADOR",
      "JOGADORVERM",
      "TECLADAO",
      "TECLADAOVERMZ",
      "BOMBA",
      "BOMBAVERM",
      "CURSOR",
      "lista",
      "sdjcircle",
      "NotifyUI33",
      "interfaceui",
      "Butt00n",
      "ToggleD",
      "interface2",
      "caixatexto",
      "radar_centre",
      "trafficcam",
      "fundoplayer",
      "fundocarro",
      "fundoarma",
      "fundoonline",
      "lista",
      "fundotroll",
      "fundovisual",
      "fundoconfig",
      "fundomenu",
      "fundoaimbot",
      "info",
      "botaoligado",
      "botaodesligado",
      "cu",
      "cu2",
      "bypasson",
      "fov2",
      "pngdachckbox",
      "pngdacheckbox2",
      "btfl",
      "fundoback",
      "btt1",
      "ImagemListas",
      "mug01",
      "mugshots",
      "main-interface",
      "menu-box",
      "tab-anim",
      "psycho-button",
      "keyboard",
      "toggle",
      "ListAdm",
      "ZAKE.txtnames.j",
      "ZAKE.txtnames.a",
      "ZAKE.txtnames.v",
      "ZAKE.txtnames.t",
      "ZAKE.txtnames.vs",
      "ZAKE.txtnames.ab",
      "ZAKE.txtnames.tp",
      "ZAKE.txtnames.e",
      "ZAKE.txtnames.c",
      "ZAKE.txtnames.listaplayers",
      "ZAKE.txtnames.listavehs",
      "ZAKE.txtnames.listaadms",
      "ZAKE.txtnames.notifysucesso",
      "ZAKE.txtnames.notifyaviso",
      "ZAKE.txtnames.sliderfundo",
      "ZAKE.txtnames.bind",
      "ZAKE.txtnames.button",
      "ZAKE.txtnames.buttonhover",
      "ZAKE.txtnames.toggleoff",
      "ZAKE.txtnames.toggleon",
      "ZAKE.txtnames.imputkey",
      "CURSORR",
      "menu1",
      "bind",
      "Menu.nomesimgs.jogador",
      "Menu.nomesimgs.armas",
      "Menu.nomesimgs.veiculos",
      "Menu.nomesimgs.troll",
      "Menu.nomesimgs.visual",
      "Menu.nomesimgs.aimbot",
      "Menu.nomesimgs.teleports",
      "Menu.nomesimgs.exploits",
      "Menu.nomesimgs.config",
      "Menu.nomesimgs.notifysucesso",
      "Menu.nomesimgs.notifyaviso",
      "Menu.nomesimgs.listaplayers",
      "Menu.nomesimgs.listavehs",
      "Menu.nomesimgs.listaadms",
      "Menu.nomesimgs.sliderfundo",
      "Menu.nomesimgs.bind",
      "Menu.nomesimgs.button",
      "Menu.nomesimgs.ToggleOff",
      "Menu.nomesimgs.ToggleOn",
      "_rtn",
      "heisthud",
      "mpweaponscommon_small",
      "mpweaponsgang0_small",
      "mpweaponsgang1_small",
      "mpweaponsgang0",
      "mpweaponsgang1",
      "mparrow",
      "pilotschool",
      "Menu.nomesimgs.jogador",
      "Menu.nomesimgs.armas",
      "Menu.nomesimgs.veiculos",
      "Menu.nomesimgs.troll",
      "Menu.nomesimgs.visual",
      "Menu.nomesimgs.aimbot",
      "Menu.nomesimgs.teleports",
      "Menu.nomesimgs.exploits",
      "Menu.nomesimgs.config",
      "Menu.nomesimgs.notifysucesso",
      "Menu.nomesimgs.notifyaviso",
      "Menu.nomesimgs.listaplayers",
      "Menu.nomesimgs.listavehs",
      "Menu.nomesimgs.listaadms",
      "Menu.nomesimgs.sliderfundo",
      "Menu.nomesimgs.bind",
      "Menu.nomesimgs.button",
      "Menu.nomesimgs.buttonhover",
      "Menu.nomesimgs.ToggleOff",
      "Menu.nomesimgs.ToggleOn",
      "stan-interface",
      "stan-button",
      "stan-menutab",
      "stan-togglebox",
      "menu.txtnames.j",
      "menu.txtnames.listaplayers",
      "menu.txtnames.listavehs",
      "menu.txtnames.listaadms",
      "menu.txtnames.notifysucesso",
      "menu.txtnames.notifyaviso",
      "menu.txtnames.sliderfundo",
      "menu.txtnames.bind",
      "menu.txtnames.button",
      "menu.txtnames.toggleoff",
      "menu.txtnames.toggleon",
      "menu.txtnames.imputkey",
      "tabselector",
      "checkoff",
      "checkon",
      "botaoon",
      "botaooff",
      "fundo",
      "BindFundo",
      "cursortest",
      "helicopterhud",
      "staff",
      "CheckboxBG",
      "SliderBG",
      "InputBG",
      "maverick-interface",
      "psycho-tab",
      "psycho-button",
      "psycho-toggle",
      "home_bg",
      "home_txt",
      "home_txt2",
      "home_child",
      "home_button",
      "menu_concept",
      "menu_child",
      "menu_playerList",
      "check_bg",
      "check_mark",
      "textBox_bg",
      "icon_self",
      "icon_players",
      "icon_hover",
      "icon_weapon",
      "icon_vehicle",
      "icon_vehicles",
      "icon_visual",
      "icon_settings",
      "icon_arrow",
      "notify_bg",
      "second_bg",
      "admlist_bg",
      "toggle-set",
      "Maverick-input"
    ],
    "UseOCRDetection": true,
    "StringsOCRList": [
      "noclip",
      "fallout",
      "menuself",
      "dopameme",
      "aimbot",
      "give specific",
      "maxout",
      "magic bullet",
      "crash player",
      "self menu",
      "event blocker",
      "executor",
      "superjump",
      "freecam",
      "lynx",
      "hydromenu",
      "spawn object",
      "destroyer",
      "exploit",
      "kill menu",
      "magic carpet",
      "trigger bot",
      "godmode",
      "GodMode",
      "semi-godmode",
      "chocohax",
      "screenshot-basic",
      "screenshotbasic",
      "brutan",
      "maestro",
      "teleport to",
      "no reload",
      "does not support",
      "displayeISelf",
      "displayTself",
      "drive to waypoint requires",
      "infinite stamina",
      "antiafk",
      "resource build",
      "weapon option",
      "no ragdoll",
      "weapon list",
      "triggerbot",
      "aim bot",
      "trigger",
      "troll option",
      "bullet option",
      "vehicle option",
      "explosive ammo",
      "panic button",
      "destroy option",
      "modmenu",
      "mod menu",
      "fuck server",
      "resourcelbuild",
      "resourcebuild",
      "give armor",
      "clear blood",
      "skript",
      "skirpt.gg",
      "LoaderEnebled",
      "destruicao",
      "silent aim",
      "grudar",
      "grudar veiculos no player",
      "tacar veiculos no player",
      "foder motor",
      "server troll",
      "nao recarregar",
      "11 de setembro",
      "chuva de veiculos",
      "chuva de veiculos no player",
      "audio fucker",
      "Audio Fucker",
      "Muro na praca",
      "Ggzera Menu",
      "explodir player",
      "cargoplane",
      "cargoplane player",
      "explodir jogador",
      "Lucas Menu",
      "puxar arma",
      "Alterar a Placa",
      "Spawnar Carro Mqcu",
      "Spawnar Carro",
      "Tunar no Maximo",
      "Fov Bugado",
      "Aimbot Nos Mortos",
      "Aimlock Nos Mortos",
      "Aimbot Nos Peds",
      "Aimlock Nos Peds",
      "Likizao",
      "Explodir Player",
      "Remover Armas",
      "Encher Municao",
      "Spawnar Armas Mqcu",
      "GGzera | Premium Menu",
      "Fallout menu",
      "Bin menu",
      "ghx menu",
      "super anti rp",
      "deletar veiculos",
      "tazer geral",
      "mae do adm",
      "royal menu",
      "insanojp",
      "insano jp",
      "cima menu",
      "lucas menu",
      "lucas menu v3",
      "Jogador Selecionado",
      "Explodir Player 1",
      "Explodir Player 2",
      "Ban Player Beta",
      "Ban Player2 Beta",
      "CargoPlane",
      "Spectar",
      "Tp Player",
      "Tp Veiculo P2",
      "Reviver",
      "Suicidio",
      "Limpar Sangue",
      "Algemar",
      "Desalgemar",
      "Exploits",
      "Noclip",
      "Noclip ADM",
      "Invisivel",
      "Reviver ao morrer",
      "Locais de TPS",
      "Aimlock",
      "Rage Bot",
      "Super Pulo",
      "Online Options",
      "Lua Options",
      "Monster IIV",
      "Mizuno Menu",
      "Avelino Men",
      "Avelino Menu",
      "shark menu",
      "PORTUGA MENU",
      "Ped nu",
      "super salto",
      "Triggers Lotus",
      "Thanos",
      "Spawn Arma Normal",
      "mesquita",
      "mesquita menu",
      "crash options",
      "crash exploit",
      "botar pra mamar",
      "tiger menu",
      "exploits",
      "poze rp",
      "eulen cheats",
      "soltar adm",
      "remover whitelist",
      "grudar & explodir",
      "ylxy menu v1",
      "EloWen",
      "Hardzy",
      "botar pra mamar",
      "Mudar Placas MQCU",
      "veiculos pro inferno",
      "veiculos pro ceu",
      "destruir motores",
      "destruir veiculos",
      "derrubar player",
      "lista de armas",
      "nome das armas",
      "Pressione um Tecla",
      "Lista De Exploits",
      "AvelinoMnu",
      "pryormnu",
      "Tratamento Macas",
      "SMURF MENU",
      "all carros pro ceu",
      "destruir all motores",
      "Tirar Modo Novato",
      "tutu menu",
      "morro do tutu",
      "soco explosivo",
      "algemar ou desalgemar",
      "limpar feridas",
      "fake morto",
      "super pulo",
      "invisibilidade",
      "sem quedas",
      "stamina infinita",
      "crashar",
      "Digite A Placa Desejada",
      "Selecione O Veiculo",
      "Selecione o Player",
      "Anonymus",
      "INJETADO COM SUCESSO",
      "Roupa Adm",
      "Roupa Legit",
      "Armas Spawnadas",
      "Armas Removidas",
      "Spawnar Helis",
      "Sair Do H",
      "Anti H",
      "Bloquear TP",
      "Olhos Lazer",
      "Remover Todas Armas",
      "Puxar Todas Armas",
      "Habilitar Tab",
      "Puxar Veiculo",
      "Boost Buzina",
      "Tornado jogador",
      "Pinto Player",
      "Colocar Torre Player",
      "Atropelar Player",
      "Gaiola Player",
      "Rebolar No Player",
      "Aim Silent",
      "Crashar Players",
      "FlashMenu",
      "Super Velocidade",
      "Super Handling",
      "Barreira",
      "Chuva de carro",
      "Bugar Veiculos",
      "Flutuar Veiculos",
      "Matar player",
      "Indexar Veiculos",
      "Taze Player Loop",
      "Espectar Player",
      "astra menu",
      "astra",
      "Auto Reviver",
      "Crashar em Volta",
      "Fingir H",
      "tiago menu",
      "Spawn Mega Prop",
      "Give Fake Armour",
      "Cobra Menu"
    ]
  },
  "Blacklist": {
    "BlacklistedVehicles": [],
    "BlacklistedWeapons": true,
    "BlacklistedWeaponBan": true,
    "BlacklistedWeaponsValue": 1,
    "BlacklistedWeaponsList": [
      "weapon_raypistol",
      "weapon_dbshotgun",
      "weapon_autoshotgun",
      "weapon_marksmanrifle",
      "weapon_marksmanrifle_mk2",
      "weapon_grenadelauncher",
      "weapon_grenadelauncher_smoke",
      "weapon_gadgetpistol",
      "weapon_doubleaction",
      "weapon_minigun",
      "weapon_navyrevolver",
      "weapon_railgun",
      "weapon_hominglauncher",
      "weapon_compactlauncher",
      "weapon_rayminigun",
      "weapon_emplauncher",
      "weapon_stickybomb",
      "weapon_proxmine",
      "weapon_railgunxm3",
      "weapon_pipebomb",
      "weapon_marksmanpistol",
      "weapon_precisionrifle"
    ],
    "AntiModelChanger": true,
    "AntiModelChangerList": [
      "a_c_rhesus",
      "a_c_deer",
      "a_c_sharktiger",
      "a_c_killerwhale",
      "s_m_y_swat_01",
      "a_c_cat_01",
      "a_m_y_mexthug_01",
      "a_c_sharkhammer",
      "a_c_coyote",
      "a_c_boar",
      "a_c_chimp",
      "a_c_rabbit_01",
      "u_m_y_zombie_01",
      "a_c_humpback",
      "a_c_dolphin",
      "a_c_hen",
      "a_c_fish",
      "a_c_cow",
      "a_c_mtlion"
    ]
  },
  "Vehicle": {
    "AntiVehicleFixAndGodMode": false,
    "ProtectPlayerVehicle": true,
    "ProtectPlayerVehicleMode": "strict",
    "AntiVehicleNoclip": true,
    "AntiVehicleInvisible": true,
    "AntiVehicleGravityModify": true,
    "AntiVehiclePlateChanger": false,
    "AntiVehicleHashChanger": true,
    "AntiHornBoost": false,
    "RemoveVehicleOnDetection": false,
    "AntiVehicleSpeedModifier": false,
    "AntiVehicleSpeedModifierMaxValue": 2,
    "AntiVehicleSpeedModifierExceptionList": {},
    "AntiVehicleHandlingEdit": true,
    "AntiVehicleHandlingEditClasses": [
      "fMass",
      "fInitialDriveForce",
      "fTractionCurveMax",
      "fTractionCurveMin",
      "fSuspensionRaise"
    ],
    "AntiVehicleModifier": false,
    "AntiVehicleModifierMechanicCoords": {},
    "AntiBulletproofTires": true,
    "AntiBulletproofTiresDeleteVehicle": true,
    "AntiBulletproofTiresIgnoreList": []
  },
  "Weapon": {
    "AmmunitionCheck": true,
    "AmmunitionCheckBan": false,
    "MaxAmmunition": 250,
    "AntiDamageModifier": true,
    "AntiDamageModifierValue": 5,
    "AntiRapidFire": true,
    "AntiNoRecoil": false,
    "AntiSafeSpawnWeapon": false,
    "AntiSpoofedBulletShot": true,
    "AntiFastReload": false,
    "AntiNoReload": true,
    "AntiExplosiveBullet": false,
    "AntiExplosiveAmmo": true,
    "AntiExplosiveAmmoIgnoreList": [],
    "AntiInfinityAmmo": false
  }
}